server:
  port: 28000

web:
  client:
    enabled: true
    target-url: http://localhost:28000/esb/api/summary
    call-back-url: http://localhost:28000/esb/api/proxy

tcp:
  server:
    proxy:
      enabled: true
      bind-port: 9999
  client:
    async-connction:
      enabled: true
      host: 127.0.0.1
      port: 5555
      reconnectDelaySec: 10

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2db/testdb
    driver-class-name: org.h2.Driver
    username: ENC(TdkY5c5vuDw4llaCxKBir12X/yRhf2xBZAnzN6m+ZioVuqFz+5Z8QJN30jsrhwDT)
    password: ENC(I1YqvtB1542Z7FFWOIrm595nSO7jMF0kvOhiULJgu7URunH0MPLNAJQIwKeuTQXJ)
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: mb.fw.net.policeminwon.web.mapper
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    allow-bean-definition-overriding: true
