server:
  port: 38000

web:
  client:
    enabled: true
    target-url: http://localhost:38000

tcp:
  encoding: MS949
  server:
    proxy:
      enabled: true
      bind-port: 9999
  client:
    async-connction:
      enabled: true
      connections:
        - system-code: KFT
          host: 127.0.0.1
          port: 5555
          reconnect-delay-sec: 36000
        - system-code: TCS
          host: 127.0.0.1
          port: 7777
          reconnect-delay-sec: 36000
        - system-code: ESB
          host: 127.0.0.1
          port: 9999
          reconnect-delay-sec: 3600000

jms:
  logging:
    enabled: false
spring:
  profiles:
    active: proxy
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#server:
#  port: 28100
#
#spring:
#  profiles:
#    active: summary
#  main:
#    allow-bean-definition-overriding: true
#
#web:
#  client:
#    enabled: true
#    call-back-url: http://localhost:28000/esb/api/proxy
#
#mybatis:
#  mapper-locations: classpath:ViewBillingDetailMapper.xml
#  type-aliases-package: mb.fw.policeminwon.entity
#  map-underscore-to-camel-case: true

